### ISSUE TITLE
TOVÁBBI ÜGYFÉLNÉL SEM MEGY A RENDSZER!!! NEM KAPUNK VÁLASZOKAT A NAV-tól!!!

### ISSUE THREAD

**Issue by robozb** [nav-gov-hu/Online-Invoice#1128]
Egyik nap ment, másik nap már kakukk, semmi, hibát apunk vissza, az ég világon nem módosítottunk semmit, különböző rendszerek, különböző felhasználók, különböző adószámok!!!

Üzenet:
**********************
Hiba!
(Message: Ervenytelen TokenExchangeResponse!)

Nyomkövetés:
**********************
java.lang.Exception: Ervenytelen TokenExchangeResponse!

	at nav.online.teszt.wfs.hu.onlineszamla.NAVOnlineSzamlaTovabbito$TokenIgenyles.keresASzervertol(NAVOnlineSzamlaTovabbito.java:463)

	at nav.online.teszt.wfs.hu.onlineszamla.NAVOnlineSzamlaTovabbito.szamlaBekuldes_Created(NAVOnlineSzamlaTovabbito.java:180)

	at cur.gui.resztvevok.Pnl_Resztvevolista.gmb_SzamlaOnlineSzamlaTovabbitasActionPerformed(Pnl_Resztvevolista.java:3126)

	at cur.gui.resztvevok.Pnl_Resztvevolista.access$3600(Pnl_Resztvevolista.java:99)

	at cur.gui.resztvevok.Pnl_Resztvevolista$32.actionPerformed(Pnl_Resztvevolista.java:906)

	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)

	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)

	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)

	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)

	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)

	at java.awt.Component.processMouseEvent(Unknown Source)

	at javax.swing.JComponent.processMouseEvent(Unknown Source)

	at java.awt.Component.processEvent(Unknown Source)

	at java.awt.Container.processEvent(Unknown Source)

	at java.awt.Component.dispatchEventImpl(Unknown Source)

	at java.awt.Container.dispatchEventImpl(Unknown Source)

	at java.awt.Component.dispatchEvent(Unknown Source)

	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)

	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)

	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)

	at java.awt.Container.dispatchEventImpl(Unknown Source)

	at java.awt.Window.dispatchEventImpl(Unknown Source)

	at java.awt.Component.dispatchEvent(Unknown Source)

	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)

	at java.awt.EventQueue.access$500(Unknown Source)

	at java.awt.EventQueue$3.run(Unknown Source)

	at java.awt.EventQueue$3.run(Unknown Source)

	at java.security.AccessController.doPrivileged(Native Method)

	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)

	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)

	at java.awt.EventQueue$4.run(Unknown Source)

	at java.awt.EventQueue$4.run(Unknown Source)

	at java.security.AccessController.doPrivileged(Native Method)

	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)

	at java.awt.EventQueue.dispatchEvent(Unknown Source)

	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)

	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)

	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)

	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)

	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)

	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by robozb** [comment]
Kérnék visszahívást: 06 70 31 55 201
Köszönöm!

**Comment by robozb** [comment]
Megjavult "magától" (a NAV rendszereiben)
